# Generated by Django 2.2.2 on 2020-10-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
